#  Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.1.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run ci
      - run: BASE_URL=$CIRCLE_BRANCH npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    docker:
      - image: circleci/node:10.1.0
    steps:
      - attach_workspace:
         at: dist
      - run:
          name: Deploy Over SSH to feature dir
          command: |
              scp -o StrictHostKeyChecking=no -rp dist/* $SSH_USER@$SSH_HOST:$PATH_TO_DIST/$CIRCLE_BRANCH/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /feature-.*/
